angular.module('myApp')

    .config(function ($translateProvider) {
        $translateProvider.translations('en', {
            COMPANY_NAME1: 'Aluminum',
            COMPANY_NAME2: 'Construction',
            FOR_EVERY_POSSIBLE: 'For every possible reason',
            REASON1: 'We plan, manufacture and install our screen walls for you, our valued customer, using the most cutting-edge technology available today.',
            REASON2: 'We accompany you throughout every stage: building design, construction, and ongoing maintenance.',
            REASON3: 'We have been planning, producing and installing screen walls for over 30 years, adapting them to each unique client and project requirements.',
            REASON4: 'We are renowned for our uncompromising adherence to product quality, high finishing standards and impeccable service.',
            REASON5: 'Our products comply with Israeli, European and American standards.',
            REASON6: 'We believe in our products so completely, that you receive a lifetime guarantee.',
            YEAR_ESTABLISHED: 'Year Established',
            OVER: 'Over',
            M2: 'm2',
            CURTAIN_WALLS: 'Curtain Walls',
            PROJECTS: 'Projects',
            SUCCESS: 'Success',
            DESC: 'Aluminum Construction is a leader in planning, manufacturing and installing complex sheaths for office towers and public buildings in Israel and around the world. The company belongs to the Aluminum Construction Holdings Ltd Group, founded in 1991. Its technological developments and products have set new standards of quality and innovation in the worldwide curtain wall industry.',
            ADDRESS: '8 Ophira St., Mishor Adumim Industrial Zone 9851106 Israel',
            TEL: 'Tel:',
            TEL_N: '972-2-5352581',
            FAX: 'Fax:',
            FAX_N: '972-2-5354008',
            ABOUT0: 'About',
            TECHNOLOGY: 'Technology',
            CONTACT: 'Contact Us',
            ABOUT: 'About the Company',
            ABOUT1:'is a leader in planning, manufacturing and installing complex sheaths for office towers and public buildings. The company belongs to the Aluminum Construction Holdings Ltd Group. The company develops, designs, produces and implements glass and aluminum products for widespread applications, such as residential towers, skylights, and cable and steel walls. The group was established in 1991 by its founder and CEO, Mr. Rami Boneh. ',
            ABOUT2:'is active in the curtain wall industry and specializes in carrying out projects in the public building and office building sector in Israel and around the world. The company’s emphasis is on customer needs and satisfaction. Its products are highly advanced as well as environment-friendly.',
            ABOUT3:'does not compromise on the quality of its products, and meets Israeli, European and American standards. All products are tested in the group’s laboratory, which is considered one of the three top labs in the world. The company’s technological developments and products have set new standards of quality and innovation in the worldwide curtain wall industry.',
            COMPANY_VALUES: 'Company Values',
            VAL_KEY1: 'Innovation',
            VALUE1:'We are constantly developing new ideas. Our vast experience and professional knowhow enable us to develop cutting-edge technologies and products, and to provide you with creative solutions. Our innovative, economical, “green” products are considered breakthroughs and stand at the technological forefront of the local and global curtain wall industry.',
            VAL_KEY2: 'Professionalism and Service',
            VALUE2:'Our company has been manufacturing and installing curtain walls for over 30 years. We will accompany you every step of the way, from the planning stage through construction and maintenance. Customer requirements and adherence to timetables are always a top priority. Our personnel are excellent, reliable professionals – you’re in great hands! ',
            VAL_KEY3: 'Product Quality',
            VALUE3:'never compromises on quality! Our products comply with the highest Israeli, European and American standards. All products are tested in the company laboratory, which is considered one of the three top labs in the world. We believe so strongly in our product quality and level of finishing – that you receive a lifetime guarantee.',
            ADDRESS2: '8 Ophira St., Mishor Adumim Industrial Zone. ZIP Code: 98100, Israel',
            EMAIL: 'Email:',
            NAME: 'Name:',
            MESSAGE: 'Message:',
            SEND: 'Send',
            SARONA: 'Azrieli Sarona',
            AMOT: 'Amot Atrium Tower',
            PLATINUMTOWER: 'Platinum Tower',
            azrieliSquerTower: 'Azrieli Square Tower',
            quiryatHamemshala: 'Government Tower',
            discountTower: 'Discount Tower',
            levinsteinTower: 'Levinstein Tower',
            museumTower: 'Museum Tower',
            shoftimTower: 'Hashoftim Tower',
            veredTower: 'Vered Tower',
            concordTower: 'Concord Tower',
            azrieliCenterHolon: 'Azrieli Center Holon',
            petahTikvaTower: 'Migdal',
            tamarPark: 'Tamar Park',
            yesPlanet: 'Yes Planet',
            cityGate: 'City Gate Tower',
            tradeTower: 'Trade Tower',
            sapTower: 'S.A.P Tower',
            twinTowers: 'Twin Towers',
            mercury: 'Mercury',
            azorimPark: 'Azorim Park',
            ashdar2000: 'Ashdar 2000 (1+2)',
            azrieliModin: 'Azrieli Mall Modi\'in',
            azrieliOrYehuda: 'Terminal Center',
            azrieliAkko: 'Azrieli mall Akko',
            azrieliMallAta: 'Azrieli Mall K. ATA',
            azrieliRamla: 'Azrieli Mall Ramla',
            DOWNLOAD: 'Download the catalog',
            Azrieli_co: 'Azrieli Group Ltd',
            DavidAzrieleArchMosheTzurArch: 'David Azrieli Arch., Moshe Tzur Arch.',
            AmotInvestmentsLtd: 'Amot Investments Ltd',
            MosheTzurArch: 'Moshe Tzur Arch.',
            LeaRubanenkoArch: 'Lea Rubanenko Arch.',
            DavidAzrieliArchMooreYaskySivanArch: 'David Azrieli Arch., Moore Yasky Sivan Arch.',
            AfricaMinrav: 'Africa Minrav',
            BenpelegArchZafrirGananiArch: 'Ben peleg Arch., Zafrir Ganani Arch.',
            LevinsteinCo: 'Levinstein Co',
            MooreYaskySivanArch: 'Moore Yasky Sivan Arch.',
            MooreYaskySivanArchRazielArch: 'Moore Yasky Sivan Arch., Raziel Arch.',
            RapaportArch: 'Rapaport Arch.',
            MigdalLtd: 'Migdal Ltd',
            ZviGabaiArch: 'Zvi Gabai Arch.',
            Gindi: 'Gindi',
            RaniZissArch: 'Rani Ziss Arch.',
            IsralomPropertiesLtd: 'Isralom Properties Ltd',
            AfricaIsrael: 'Africa Israel',
            MigdalInsuranceLtd: 'Migdal Insurance Ltd',
            GabaiArch: 'Gabai Arch.',
            Ruhrberg:'Ruhrberg Constracting and Investments Ltd',
            IsraelTheatersLtd: 'Israel Theaters Ltd',
            GoodFortuneLtd: 'Good Fortune Ltd',
            PelegArch: 'Peleg Arch.',
            AtblismntWanageLtd: 'Atblismnt Wanage Ltd',
            SAP: 'S.A.P Co.',
            RubinArch: 'Rubin Arch.',
            TwinTowersLtd: 'Twin Towers Ltd',
            MercuryCo: 'Mercury Co.',
            MannShinarArch: 'Mann Shinar Arch.',
            BritichCo: 'Britich Co',
            AshtromGroupLtd: 'Ashtrom Group Ltd',
            FintziShmuelRava: 'Fintzi Yehoshua & Shmuel Rava Arch.',
            SafadieArchitects:'Safadie Architects, David Azrieli Arch. ',
            EllaGroupInvestmentsLtd: 'Ella Group Investments Ltd.',
            MosheKirshon: 'Moshe Kirshon Arch.',
            AzrieliTzamireOko: 'David Azrieli Arch., Yigal Tzamire Arch.,Yael Oko Arch.',
            YasharArch: 'David Azrieli Arch., Yashar Arch. Avner Yashar',
            Developer: 'Developer:',
            Architect: 'Architect:'




        })
            .translations('heb', {
                COMPANY_NAME1: 'אלומיניום',
                COMPANY_NAME2: 'קונסטרקשיין',
                FOR_EVERY_POSSIBLE: 'מכל הסיבות ',
                REASON1: '	קירות המסך שלנו מתוכננים, מיוצרים ומותקנים עבורכם באמצעות הטכנולוגיות המתקדמות בעולם',
                REASON2: '	אנחנו אתכם משלב תכנון הבניין, דרך הביצוע ועד לשלב התחזוקה',
                REASON3: '	אנחנו מתכננים מייצרים ומתקינים קירות מסך מעל 30 שנה בהתאמה אישית',
                REASON4: '	אנחנו לא מתפשרים על איכות המוצר, הגימור והשירות ',
                REASON5: '	המוצרים שלנו עומדים בתקנים ישראלים, אירופאים ואמריקאים',
                REASON6: '	אנחנו מאמינים במוצרים שלנו ולכן אתם מקבלים אחריות לכל החיים',
                YEAR_ESTABLISHED: 'שנת הקמה',
                OVER: 'מעל',
                M2: 'מ"ר',
                CURTAIN_WALLS: 'קירות מסך',
                PROJECTS: 'פרוייקטים',
                SUCCESS: 'הצלחה',
                DESC: 'אלומיניום קונסטרקשיין היא חברה מובילה בתחום תכנון, ייצור ובנייה של מעטפות מורכבות למגדלי משרדים ומבני ציבור. החברה שייכת לקבוצת אלומיניום קונסטרקשיין אחזקות בע"מ שנוסדה בשנת 1991 . החברה בונה מגוון רחב של פרויקטים, בנייני משרדים ומבנים ציבוריים בארץ ובעולם. הפיתוחים הטכנולוגיים של החברה ומוצריה הציבו סטנדרטים חדשים של איכות וחדשנות בענף קירות המסך בעולם.',
                ADDRESS: 'אופירה 8 א.ת. מישור אדומים 9851106',
                TEL: 'טל:',
                TEL_N: '02-5352581',
                FAX: 'פקס:',
                FAX_N: '02-5354008',
                ABOUT0: 'אודות',
                TECHNOLOGY: 'טכנולוגיה',
                CONTACT: 'צור קשר',
                ABOUT: 'אודות החברה',
                ABOUT1: 'היא חברה מובילה בתחום תכנון, ייצור והתקנה של מעטפות מורכבות למגדלי משרדים ומבני ציבור. החברה שייכת לקבוצת "אלומיניום קונסטרקשיין אחזקות בע"מ". החברה מפתחת, מתכננת, מייצרת ומבצעת מוצרים בתחומי הזכוכית והאלומיניום לשימושים רבים כגון: מגדלי מגורים, סקיילייט, קירות כבלים ופלדה. הקבוצה נוסדה בשנת 1991 על ידי מר רמי בונה, נשיא הקבוצה.',
                ABOUT2: 'פועלת בענף קירות המסך ומתמחה בביצוע פרויקטים במבנים בסקטור הציבורי ובנייני משרדים ברחבי הארץ ובעולם. החברה שמה דגש רב על הלקוח, צרכיו ושביעות רצונו. מוצרי החברה מתקדמים וידידותיים לסביבה.',
                ABOUT3: 'לא מתפשרת על האיכות ומוצריה עומדים בתקנים ישראלים, אירופאים ואמריקאים. מוצרי החברה נבדקים במעבדת הקבוצה הנחשבת לאחת משלוש המעבדות המובילות בעולם. הפיתוחים הטכנולוגיים של החברה ומוצריה הציבו סטנדרטים חדשים של איכות וחדשנות בענף קירות המסך בעולם.',
                COMPANY_VALUES: 'ערכי החברה',
                VAL_KEY1: 'חדשנות',
                VALUE1: 'אנחנו מתחדשים כל הזמן. הניסיון והידע המקצועי שלנו מאפשר לנו לספק לכם פתרונות ולפתח טכנולוגיות ומוצרים מתקדמים. המוצרים שלנו חדשניים, חסכוניים וידידותיים לסביבה ולכן נחשבים לפורצי דרך ומובילים טכנולוגית את ענף קירות המסך בארץ ובעולם.',
                VAL_KEY2: 'מקצועיות ושירות',
                VALUE2: 'חברתנו מתכננת, מייצרת ומבצעת קירות מסך כבר מעל ל –30 שנים. אנחנו נלווה אתכם לאורך כל הדרך משלב התכנון והייצור ועד לביצוע הפרויקט ותחזוקתו. צרכי הלקוחות ועמידה בלוחות זמנים נמצאים אצלנו במקום הראשון. כח האדם שלנו איכותי, מקצועי ומיומן  - אתם בידיים טובות!',
                VAL_KEY3: 'איכות המוצר',
                VALUE3: 'אצלנו לא מתפשרים על האיכות! המוצרים שלנו עומדים בסטנדרטים הגבוהים ביותר ובתקנים הישראלים, האירופאים והאמריקאים. כל המוצרים נבדקים במעבדת החברה הנחשבת לאחת משלוש המעבדות המובילות בעולם. אנחנו מאמינים באיכות המוצרים וברמת הגימור שלנו ולכן אתם מקבלים אחריות לכל החיים.',
                ADDRESS2: 'רחוב אופירה 8, אזור תעשייה מישור אדומים. מיקוד: 98100, ישראל',
                EMAIL: 'דוא"ל:',
                NAME: 'שם:',
                MESSAGE: 'הודעה:',
                SEND: 'שלח',
                SARONA: 'מגדל שרונה',
                AMOT: 'מגדל אמות אטריום',
                PLATINUMTOWER: 'מגדל פלטינום',
                azrieliSquerTower: 'מגדל עזריאלי מרובע',
                quiryatHamemshala: 'מגדל קרית הממשלה',
                discountTower: 'מגדל דיסקונט',
                levinsteinTower: 'מגדל לוינשטיין',
                museumTower: 'מגדל המוזיאון',
                shoftimTower: 'מגדל השופטים',
                veredTower: 'מגדל הוורד',
                concordTower: 'מגדל קונקורד',
                azrieliCenterHolon: 'מתחם עזריאלי חולון',
                petahTikvaTower: 'בית מגדל פ"ת',
                tamarPark: 'פארק תמר',
                yesPlanet: 'יס פלאנט',
                cityGate: 'מגדל שער הסיטי',
                tradeTower: 'מגדל הטרייד טאוור',
                sapTower: 'מגדל שאפ',
                twinTowers: 'מגדלי התאומים',
                mercury: 'מרקורי',
                azorimPark: 'פארק אזורים',
                ashdar2000: 'אשדר 2000 בניין 1+2',
                azrieliModin: 'קניון עזריאלי מודיעין',
                azrieliOrYehuda: 'טרמינל סנטר - אור יהודה',
                azrieliAkko: 'עזריאלי עכו כדור',
                azrieliMallAta: 'עזריאלי קריית אתא כדור',
                azrieliRamla: 'עזריאלי רמלה - כדור זכוכית',
                DOWNLOAD: 'להורדת קטלוג',
                Azrieli_co: 'קבוצת עזריאלי',
                DavidAzrieleArchMosheTzurArch: 'אדר\' דוד עזריאלי, משה צור אדריכלים',
                AmotInvestmentsLtd: 'אמות השקעות בע"מ',
                MosheTzurArch: 'משה צור אדריכלים',
                LeaRubanenkoArch: 'לאה רובננקו אדריכלים',
                DavidAzrieliArchMooreYaskySivanArch: 'אדר\' דוד עזריאלי, יסקי מור סיון אדריכלים',
                AfricaMinrav: 'אפריקה ישראל/מנרב',
                BenpelegArchZafrirGananiArch: 'בן פלג אדריכלים, צפריר גנני אדריכלים',
                LevinsteinCo: 'משולם לוינשטיין',
                MooreYaskySivanArch: 'יסקי מור סיון אדריכלים',
                MooreYaskySivanArchRazielArch:'יסקי מור סיון אדריכלים/ אודי רזיאל אדריכל',
                RapaportArch: 'רפפורט אדריכלים',
                MigdalLtd: 'חברת מגדל',
                ZviGabaiArch: 'צבי גבאי אדריכלים',
                Gindi:'חברת גינדי',
                RaniZissArch: 'רני זיס אדריכלים',
                IsralomPropertiesLtd: 'ישראלום נכסים',
                AfricaIsrael: 'אפריקה ישראל',
                MigdalInsuranceLtd: 'חברת ביטוח מגדל',
                GabaiArch: 'גבאי אדריכלים',
                Ruhrberg:'רורברג השקעות ובניה',
                IsraelTheatersLtd: 'תיאטראות ישראל',
                GoodFortuneLtd: 'מזל וברכה בע"מ',
                PelegArch:'פלג אדריכלים',
                AtblismntWanageLtd: 'אטבליסמנט ניהול',
                SAP: 'קבוצת שאפ',
                RubinArch: 'רובין אדריכלים',
                TwinTowersLtd: 'מגדלי התאומים בע"מ',
                MercuryCo: 'מרקורי בע"מ',
                MannShinarArch: 'מן שנער אדריכלים',
                BritichCo: 'ריט ישראל בע"מ',
                AshtromGroupLtd:'קבוצת אשטרום',
                FintziShmuelRava: ' פינצי רווה אדריכלים',
                SafadieArchitects:'משה ספדיה אדריכלים',
                EllaGroupInvestmentsLtd: 'אלה השקעות',
                MosheKirshon: 'משה קירשון אדריכלים',
                AzrieliTzamireOko:  'אדר\' דוד עזריאלי, יגאל צמיר, יעל אוקו אדריכלים',
                YasharArch: 'אדר\' דוד עזריאלי, אבנר ישר אדריכלים',
                Developer: 'יזם:',
                Architect: 'אדריכל:'



            });
        $translateProvider.preferredLanguage('heb');
    });




